# Generated by Django 5.0.6 on 2024-05-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Escola', '0002_alter_aluno_data_nascimento_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='ano',
        ),
    ]
